///|
let parquet_magic_0 = b'P'

///|
let parquet_magic_1 = b'A'

///|
let parquet_magic_2 = b'R'

///|
let parquet_magic_3 = b'1'

///|
let parquet_type_boolean = 0

///|
let parquet_type_int32 = 1

///|
let parquet_type_int64 = 2

///|
let parquet_type_int96 = 3

///|
let parquet_type_float = 4

///|
let parquet_type_double = 5

///|
let parquet_type_byte_array = 6

///|
let parquet_type_fixed_len_byte_array = 7

///|
let repetition_required = 0

///|
let repetition_optional = 1

///|
let repetition_repeated = 2

///|
let converted_type_utf8 = 0

///|
let encoding_plain = 0

///|
let encoding_plain_dictionary = 2

///|
let encoding_rle = 3

///|
let encoding_delta_binary_packed = 5

///|
let encoding_delta_byte_array = 7

///|
let encoding_rle_dictionary = 8

///|
let codec_uncompressed = 0

///|
let page_type_data_page = 0

///|
let page_type_dictionary_page = 2

///|
let page_type_data_page_v2 = 3

///|
let thrift_wire_stop = 0

///|
let thrift_wire_bool = 1

///|
let thrift_wire_byte = 2

///|
let thrift_wire_i16 = 3

///|
let thrift_wire_i32 = 4

///|
let thrift_wire_i64 = 5

///|
let thrift_wire_double = 6

///|
let thrift_wire_binary = 7

///|
let thrift_wire_list = 8

///|
let thrift_wire_set = 9

///|
let thrift_wire_map = 10

///|
let thrift_wire_struct = 11

///|
let thrift_compact_stop = 0

///|
let thrift_compact_bool_true = 1

///|
let thrift_compact_bool_false = 2

///|
let thrift_compact_byte = 3

///|
let thrift_compact_i16 = 4

///|
let thrift_compact_i32 = 5

///|
let thrift_compact_i64 = 6

///|
let thrift_compact_double = 7

///|
let thrift_compact_binary = 8

///|
let thrift_compact_list = 9

///|
let thrift_compact_set = 10

///|
let thrift_compact_map = 11

///|
let thrift_compact_struct = 12
